backend:
  name: github
  repo: valarie-lim/sampan.house
  branch: main
  base_url: https://sampan-house.vercel.app 
  auth_endpoint: api/auth

media_folder: "public/menu" 
public_folder: "/menu"      

collections:
  - name: "restaurant_menu"
    label: "Restaurant Menu"
    description: "Upload your menu file here. **Note: The file must be named exactly 'menu.pdf'**"
    files:
      - name: "menu_data"
        label: "Latest Menu Upload [PDF only]"
        file: "public/menu/menu-config.md" # Decap saves a tiny tracking file here
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Restaurant Menu" }
          - { label: "Upload Latest Menu PDF", name: "menu_pdf", widget: "file" }
